name: Deploy client to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "client/**"
      - ".github/workflows/deploy-pages.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - run: npm ci
      - run: npm run build
      - run: cp dist/index.html dist/404.html

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/dist
          publish_branch: gh-pages
