name: Notify server after Pages deploy

on:
  workflow_run:
    workflows: ["Deploy client to GitHub Pages"]
    types: [completed]

jobs:
  ping:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: POST /refresh-menu
        run: |
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "X-Deploy-Token: ${{ secrets.DEPLOY_TOKEN }}" \
            -d "{\"buildId\":\"${{ github.run_number }}\"}" \
            "${{ secrets.SERVER_REFRESH_URL }}"
